### ISSUE TITLE
Refactoring GUI layouts

### ISSUE THREAD

**Issue by LemurPwned** [LemurPwned/spintronics-visual#103]
- [x] Windows are spawned out of scope. They must be always  spawned in the center and on the top. No exceptions.
- [x]  Delete widget menu should be more user friendly: instead delete  Widget0 make smth like delete Widget 1 etc.
- [x] Add colour palette to matplotlib and betterplot colour selectors
- [x] Buttons menu must be added that will incorporate shortkey functionality from OpenGL
- [x] Rename Reset in Player Window to Stop

**Comment by pawelkulig1** [comment]
Partly done.

**Comment by pawelkulig1** [comment]
Part of it on branch #iss103

**Comment by LemurPwned** [comment]
Buttons will be managed by me from within widget constructors

**Comment by LemurPwned** [comment]
Still pull request #108
