### ISSUE TITLE
OpenGL Camera functionality

### ISSUE THREAD

**Issue by LemurPwned** [LemurPwned/spintronics-visual#105]
Camera must be altered in a following fashion:
- [x] OpenGL must allow to rotate object in depth
- [x] Camera reset key must be linked to a physical button.
- [x] Instead of moving a camera, user should move an object (drag motion)

**Comment by pawelkulig1** [comment]
I think reset button is already linked to "r" key. I don't understand first one. Third: I think user is not able to distinguish current solution from this one.

**Comment by LemurPwned** [comment]
Right now rotation is only sideways not in plane. Yeah reset is linked to a key bug not a button I think it is pretty straightforwafd

**Comment by pawelkulig1** [comment]
I think you don't understand, basing on rotation manner one can't tell if camera is rotating or object. This is only distinguishable by seeing that rotation can happen even if we don't drag&drop over object. Fixing that is not an easy thing and will require a lot of work. I don't think it's worth that but ok.

**Comment by LemurPwned** [comment]
Well right bow you can obviously tell since when you grab context and drag then it is camera moving relative to that position. It does not matter how it is implemented, the feel however is that the camera is being moved not the object
