### ISSUE TITLE
Request: a button for deleting all windows

### ISSUE THREAD

**Issue by JakubChecinski** [LemurPwned/spintronics-visual#128]
If it's a lot of work, it's probably not worth it. But I can already tell it would be a useful thing to have, so if it's simple we can consider it. 

Edit -> Delete all windows

**Comment by LemurPwned** [comment]
This can be easily done. Such an enahcement would delete all windows, but it would not collapse the grid to a single one, does it make sense in that way?

**Comment by JakubChecinski** [comment]
Yes, that's what I had in mind. Leave the grid structure untouched (whether it's 1,2 or 4 windows) and clear all widgets.
