### ISSUE TITLE
Large green shape in 3D Cubic after setting "size" to 1

### ISSUE THREAD

**Issue by JakubChecinski** [LemurPwned/spintronics-visual#129]
3D Arrow widgets with different "size" values:
https://imgur.com/j0WOqp0

Window1: size 1
Window1: size 5
Window1: size 3
Window1: size 2

I was able to reproduce the issue multiple times but the shape sometimes appeared black or blue instead of green (?)

**Comment by JakubChecinski** [comment]
You are right, they are not arrows but a 3D Cubic structure. I'm sorry for causing confusion.

Unfortunately, the problem seems to be random. Using identical data and identical settings, the shape sometimes appears and sometimes it doesn't - I don't understand why. I'm afraid the issue may be difficult to fix it because of that. 

One way to increase the probability of getting the shape seems to be setting Decimate to maximum and Size to minimum in the 3D Cubic widget window (other options untouched). But it doesn't always work, and sometimes I will also get shapes for lower Decimate values or without using Decimate at all.

Another collection of shapes, this time mostly black: https://imgur.com/a/RXDnIgW
Window 1 is Decimate to maximum and Size to minimum, no shape
Window 2 is Decimate to maximum and Size to minimum, shape visible
Window 3 is Decimate set to 2 and Size to minimum, shape visible
Window 4 is Decimate to maximum and Size to minimum, shape visible but different from window 2

**Comment by LemurPwned** [comment]
It seems that I cannot reproduce it.
From the setup settings I can deduce that it happens at minimum size.
Does it make sense to allow the user to change size for less than maximum (smooth surface)? If not, we could resolve this by locking the size to the maximum.
