### ISSUE TITLE
AppCrash: list index out of range

### ISSUE THREAD

**Issue by JakubChecinski** [LemurPwned/spintronics-visual#136]
**Describe the bug**
The app crashes for 2D_Layer and single file

**Indicate the dataset**
Example->0200nm->first file from the directory

**To Reproduce**
1. Load data
2. Add widget -> 2D_Layer
3. Don't change anything and click ok
4. App crashes

**Screenshots**
https://imgur.com/58C84B2

**Comment by LemurPwned** [comment]
OOps I have forgotten that Layer counts as 3d structure. I will fix it in a minute
