### ISSUE TITLE
Delete all windows doesn't delete 

### ISSUE THREAD

**Issue by JakubChecinski** [LemurPwned/spintronics-visual#138]
**Describe the bug**
Clicking "delete all windows" restores the "add widget" button, but doesn't actually delete the graphics.

**Indicate the dataset**
A single file from Example->0200nm 

**To Reproduce**
1. Load data
2. Add widget (I used 2D_Layer I think?)
3. Click delete all windows

**Screenshots**
https://imgur.com/B7ZyTlr
https://imgur.com/FPPKpIJ

**Comment by LemurPwned** [comment]
This happens only if there was a single widget active? I.e. for example there might be 4 grid but only one widget has been actually added?

**Comment by JakubChecinski** [comment]
No, it happens with 4 widgets as well.
https://imgur.com/M5NBs7h

If I click delete window (single window or all of them) again, then things start to become weird:
https://imgur.com/uLyvnTS

**Comment by JakubChecinski** [comment]
Important update: this problem occurs for all 3D structures, but not for 2D_Layer!
