### ISSUE TITLE
3D_Vector vanishes when HyperContrast is chosen

### ISSUE THREAD

**Issue by JakubChecinski** [LemurPwned/spintronics-visual#140]
**Describe the bug**
3D_Vector displays an empty background when HyperContrast is chosen. Resetting doesn't help. The problem occurs only when using multiple widgets grid (both 2 and 4 widgets) - for a single widget HyperContrast is working and looks pretty nice. 

**Indicate the dataset**
Example->0200nm

**To Reproduce**
1. Load data
2. Choose multiple widgets grid <- mandatory!!!
3. Load 3D_Vector widget with HyperContrast on

**Expected behavior**

**Screenshots**
https://imgur.com/1R0srDS
2nd panel: with HyperContrast
4th panel: without HyperContrast

**Comment by LemurPwned** [comment]
Please let me know if this issue still presists for you.
I think that the sole problem was that 2DLayer widget code modified global color vectors.
Did it happen solely when 2D layer was displayed?

**Comment by JakubChecinski** [comment]
It didn't occur to me to check it, but yes it's possible. It would also explain why 3D_Vector was working correctly for a single widget. 

Now it works correctly even with 2D_Layer.

**Comment by LemurPwned** [comment]
Ok, I'm closing then
