### ISSUE TITLE
Can we get independent text boxes in different widgets?

### ISSUE THREAD

**Issue by JakubChecinski** [LemurPwned/spintronics-visual#148]
I'm not sure if this is a bug or an intended feature, but right now introducing the text box into one widget introduces it everywhere for me (identical copies of the same text box appear in all widgets at the same positions). The text boxes cannot be edited independently, either. This is a significant limit for their functionality, would it be very difficult to have a separate box for each widget?

Bonus version if we can get multiple independent boxes even inside one widget (also impossible now for me). 

Screenshot: https://imgur.com/a/yfCxnAj

**Comment by LemurPwned** [comment]
It is not a bug. Widget text is currently global for a given session. We can introduce text boxs separately for each window - with new toolbars it will be quite simple to do
