### ISSUE TITLE
After loading data with no graph, no message in Plot menu

### ISSUE THREAD

**Issue by pawelkulig1** [LemurPwned/spintronics-visual#27]

**Comment by LemurPwned** [comment]
Please check if new solution on master does solve that. Unless it's a branch problem

**Comment by pawelkulig1** [comment]
Unfortunately newest master is not working for me, cause is Cython.

**Comment by LemurPwned** [comment]
Run the command in the folder cython_modules

Python3 setup.py build_ext --inplace

**Comment by pawelkulig1** [comment]
Thanks, I will add it to Readme.md, in master version this bug still exists.

**Comment by LemurPwned** [comment]
Good idea, I will later enforce makefile on cython modules at startup.

**Comment by pawelkulig1** [comment]
I will try to merge master to my branch, and after fixing I will give you pull requests.

**Comment by pawelkulig1** [comment]
Issue fixed on branch successfully merged with master, I think we can close it.
