### ISSUE TITLE
3D OpenGL and GUI

### ISSUE THREAD

**Issue by pawelkulig1** [LemurPwned/spintronics-visual#35]
- [ ] There is problem, when One changes Performance options and closes the window and then reopens it,  GUI is reloaded so it seems no changes were made. 
- [ ] Another thing is that I think changes should happen dynamically, when I change something in performance tab it should instantly reload OpenGL pane and show actual state. 
- [x] If above is not possible to make, disable performance tweaking after OpenGL is setUp and add note about that. Something like "Changes in performance settings may be applied only before animation setup. 
- [x] It would be nice if changes made are saved to file and later loaded from it, so once user sets changes they will remain set, even after program restart but it is general thing and maybe I will add API to improve that.

**Comment by LemurPwned** [comment]
I will tske this issue

**Comment by LemurPwned** [comment]
Close for now, because the feature is not easily implemented and is not really needed for now
