### ISSUE TITLE
Alter parsing handler

### ISSUE THREAD

**Issue by LemurPwned** [LemurPwned/spintronics-visual#50]
Parsing functions should handle situation where there is no .odt file, more than one and single video file.

- [ ] No .odt / .txt file in directory
- [x] More than one .odt / .txt file
- [x] Accept a single .odt / .txt or a single .ovf / .omf

**Comment by pawelkulig1** [comment]
Correct me if I am wrong:
No .odt means we cannot plot 2D plot, all other widgets should work properly.
How to handle more than one .odt file? User has to pick one? or give him ability to plot from 2 different sources?

**Comment by pawelkulig1** [comment]
If we pick one .odt/.txt file, then app should block 3D widgets.
If we pick one .ovf/.omf file app should block plot because it doesn't make sense.
Is that correct?

**Comment by LemurPwned** [comment]
Not quite,
If there is only one .odt file app should behave as it is right now, provided there are no .omf or .ovf files.

BUT if there is just one .ovf or .omf file and there is an .odt file then we should allow iterating only on plots. 
This is somehow conjugated with the issue of invalid data change on iteration.

**Comment by pawelkulig1** [comment]
single odt, omf, ovf fixed on branch #53 waiting for merge.

**Comment by LemurPwned** [comment]
I will handle this if you dont mind
