### ISSUE TITLE
Extra GL features

### ISSUE THREAD

**Issue by LemurPwned** [LemurPwned/spintronics-visual#52]
- [x] add text to display
- [x] display current frame
- [x] display FPS

**Comment by pawelkulig1** [comment]
I can take that after I am done with things assigned to me already.

**Comment by LemurPwned** [comment]
I will take this since much time has passed.

**Comment by pawelkulig1** [comment]
I was trying to do something about this but poor documentation and everything being obsolete it's more guessing than coding.

**Comment by LemurPwned** [comment]
Basically done but I have problems with adjusting z dimension, idk why but it is quite difficult to adjust. It seems that glRasterPosition sets up Camera position instead of world map positions
