### ISSUE TITLE
3D arrows crashing app

### ISSUE THREAD

**Issue by pawelkulig1** [LemurPwned/spintronics-visual#58]
if decimate is not None:
----# this is arbitrary
----self.spacer *= decimate*3

but spacer is used only here.

**Comment by LemurPwned** [comment]
Yes i have fixed this. Also there is another bug ;p also fixed in newest lull request

**Comment by pawelkulig1** [comment]
Close after merge.

**Comment by LemurPwned** [comment]
Fixed in #62
