### ISSUE TITLE
Picking directory

### ISSUE THREAD

**Issue by pawelkulig1** [LemurPwned/spintronics-visual#71]
When user picks wrong directory app crashes.

**Comment by pawelkulig1** [comment]
Fixed on branch #53 but precise investigation will be needed.

**Comment by LemurPwned** [comment]
Duplicate of #69? Or it is something new?

**Comment by pawelkulig1** [comment]
New, after adding multiprocessing_parse some if/else statements changed and checking if directory is properly selected was not working, now it's working but it is far from being safe. I would call it fast fix. I will have to rethink it.
