### ISSUE TITLE
Picking Directory

### ISSUE THREAD

**Issue by pawelkulig1** [LemurPwned/spintronics-visual#90]
When picking directory like that:
<img width="440" alt="zrzut ekranu 2018-04-24 o 23 17 03" src="https://user-images.githubusercontent.com/9385131/39214779-ea360178-4815-11e8-87d9-2d3ffddc4d3c.png">
this error occurs:
<img width="826" alt="zrzut ekranu 2018-04-24 o 23 17 48" src="https://user-images.githubusercontent.com/9385131/39214799-fd14ec28-4815-11e8-8683-1f54149d6799.png">
I am not sure if it's and issue because data is picked from middle.

**Comment by LemurPwned** [comment]
Weird, that's 0200nm dataset?

**Comment by LemurPwned** [comment]
Ok, so for the record it was a serious issue. It happens so that stages are not unique in graph files (idk why, it should not be like that) so it was due to that and the fact that regex was none and it did not raise a proper error (although it should). Anyway, will be fixed in #85
